package com.zking.model;

import com.zking.model.base.BaseBookType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookType extends BaseBookType<BookType> {
	public static final BookType dao = new BookType().dao();
}
