package com.zking.model;

import com.zking.model.base.BaseFwlx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fwlx extends BaseFwlx<Fwlx> {
	public static final Fwlx dao = new Fwlx().dao();
}
