package com.zking.model;

import com.zking.model.base.BaseFwxx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fwxx extends BaseFwxx<Fwxx> {
	public static final Fwxx dao = new Fwxx().dao();
}
