package com.zking.model;

import com.zking.model.base.BaseYh;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Yh extends BaseYh<Yh> {
	public static final Yh dao = new Yh().dao();
}
