package com.zking.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookType<M extends BaseBookType<M>> extends Model<M> implements IBean {

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}
	
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}

	public void setIsvoid(java.lang.Integer isvoid) {
		set("isvoid", isvoid);
	}
	
	public java.lang.Integer getIsvoid() {
		return getInt("isvoid");
	}

}
