package com.zking.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFwxx<M extends BaseFwxx<M>> extends Model<M> implements IBean {

	public void setFwbh(java.lang.Integer fwbh) {
		set("fwbh", fwbh);
	}
	
	public java.lang.Integer getFwbh() {
		return getInt("fwbh");
	}

	public void setBt(java.lang.String bt) {
		set("bt", bt);
	}
	
	public java.lang.String getBt() {
		return getStr("bt");
	}

	public void setDz(java.lang.String dz) {
		set("dz", dz);
	}
	
	public java.lang.String getDz() {
		return getStr("dz");
	}

	public void setZj(java.lang.Integer zj) {
		set("zj", zj);
	}
	
	public java.lang.Integer getZj() {
		return getInt("zj");
	}

	public void setLxr(java.lang.String lxr) {
		set("lxr", lxr);
	}
	
	public java.lang.String getLxr() {
		return getStr("lxr");
	}

	public void setLxdh(java.lang.String lxdh) {
		set("lxdh", lxdh);
	}
	
	public java.lang.String getLxdh() {
		return getStr("lxdh");
	}

	public void setLxbh(java.lang.Integer lxbh) {
		set("lxbh", lxbh);
	}
	
	public java.lang.Integer getLxbh() {
		return getInt("lxbh");
	}

	public void setZxqk(java.lang.Integer zxqk) {
		set("zxqk", zxqk);
	}
	
	public java.lang.Integer getZxqk() {
		return getInt("zxqk");
	}

	public void setSzlc(java.lang.Integer szlc) {
		set("szlc", szlc);
	}
	
	public java.lang.Integer getSzlc() {
		return getInt("szlc");
	}

	public void setFwcx(java.lang.Integer fwcx) {
		set("fwcx", fwcx);
	}
	
	public java.lang.Integer getFwcx() {
		return getInt("fwcx");
	}

	public void setBz(java.lang.String bz) {
		set("bz", bz);
	}
	
	public java.lang.String getBz() {
		return getStr("bz");
	}

	public void setYhbh(java.lang.Integer yhbh) {
		set("yhbh", yhbh);
	}
	
	public java.lang.Integer getYhbh() {
		return getInt("yhbh");
	}

	public void setFbrq(java.util.Date fbrq) {
		set("fbrq", fbrq);
	}
	
	public java.util.Date getFbrq() {
		return get("fbrq");
	}

}
