package com.zking.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYh<M extends BaseYh<M>> extends Model<M> implements IBean {

	public void setYhbh(java.lang.Integer yhbh) {
		set("yhbh", yhbh);
	}
	
	public java.lang.Integer getYhbh() {
		return getInt("yhbh");
	}

	public void setYhzh(java.lang.String yhzh) {
		set("yhzh", yhzh);
	}
	
	public java.lang.String getYhzh() {
		return getStr("yhzh");
	}

	public void setYhmm(java.lang.String yhmm) {
		set("yhmm", yhmm);
	}
	
	public java.lang.String getYhmm() {
		return getStr("yhmm");
	}

}
