package com.zking.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public void setBookId(java.lang.Integer bookId) {
		set("book_id", bookId);
	}
	
	public java.lang.Integer getBookId() {
		return getInt("book_id");
	}

	public void setBookName(java.lang.String bookName) {
		set("book_name", bookName);
	}
	
	public java.lang.String getBookName() {
		return getStr("book_name");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setBookAuthor(java.lang.String bookAuthor) {
		set("book_author", bookAuthor);
	}
	
	public java.lang.String getBookAuthor() {
		return getStr("book_author");
	}

	public void setBookMoney(java.lang.Integer bookMoney) {
		set("book_money", bookMoney);
	}
	
	public java.lang.Integer getBookMoney() {
		return getInt("book_money");
	}

	public void setBookPress(java.lang.String bookPress) {
		set("book_press", bookPress);
	}
	
	public java.lang.String getBookPress() {
		return getStr("book_press");
	}

	public void setBookContent(java.lang.String bookContent) {
		set("book_content", bookContent);
	}
	
	public java.lang.String getBookContent() {
		return getStr("book_content");
	}

	public void setBookPicture(java.lang.String bookPicture) {
		set("book_picture", bookPicture);
	}
	
	public java.lang.String getBookPicture() {
		return getStr("book_picture");
	}

	public void setBookState(java.lang.Integer bookState) {
		set("book_state", bookState);
	}
	
	public java.lang.Integer getBookState() {
		return getInt("book_state");
	}

	public void setIsvoid(java.lang.Integer isvoid) {
		set("isvoid", isvoid);
	}
	
	public java.lang.Integer getIsvoid() {
		return getInt("isvoid");
	}

}
